<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitdd2a18069fdf12c8242dccda29e4cf72
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('BetterMessages\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \BetterMessages\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitdd2a18069fdf12c8242dccda29e4cf72', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \BetterMessages\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitdd2a18069fdf12c8242dccda29e4cf72', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\BetterMessages\Composer\Autoload\ComposerStaticInitdd2a18069fdf12c8242dccda29e4cf72::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \BetterMessages\Composer\Autoload\ComposerStaticInitdd2a18069fdf12c8242dccda29e4cf72::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
